stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
  script:
    - docker build -t hotelsapi .

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-prod.yml up -d
    - docker exec booking_nginx nginx -s reload