services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    networks:
      - myNetwork
    volumes:
      - .:/app

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    command: "celery -A app.tasks.celery_app.celery_instance worker --loglevel=info"
    volumes:
      - .:/app

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    command: "celery -A app.tasks.celery_app.celery_instance beat --loglevel=info"
    volumes:
      - .:/app

networks:
  myNetwork:
    external: true